language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- npm install -g bower firebase-tools karma-cli yarn
install:
- yarn install --flat
- bower install
- cd functions && yarn install
- cd ..
- cd gulp && yarn install
- cd ..
script:
- cd gulp
- xvfb-run karma start karma.conf.js --single-run
before_deploy:
- cd ..
- export VERSION=$(node -p -e "require('./package.json').version")
- npm run build-production
- cd gulp && ./node_modules/.bin/sentry-cli releases new "$VERSION"
- cd ..
deploy:
- provider: firebase
  skip_cleanup: true
  project: devfestph
  token:
    secure: Z+qOhhwpkAvvfoxQA6Nt6hz4exPFQWhwZlWsjRIhmC6D5bmmgC+ypMXjV1TP92pnjYjCkeXBUy9xhiA2NphSTYzzU/ROTV3ZxptLlCMQJNBtHS269owL7PuSc7UC1xJ+y4z19ypAMVUlvhxM0I5kYmr5JFy0C6MHAqTlbuP1iWoccM4yik8t32azarw4fnSxcg258DlD472kzmgkg2rmMrrC8HEIFb/KWHnCIJN5at5B4KCFPf52kiYUCa88MBwtsBOXyO0bvmJAQP6RAuExpelw8VvdVpdJZPrJ9z9s+K8f1PQA2y6To2Q7aR/kicJJo0YRw4TXdkSWOP1cQUThEjUMVPmOvEnz+Ty+vvK+XWhgBKIHAdJqwT7WlrSl0GBdOBl7kTI7JGwDv+Spmk/QRYV/qtoZjNEuK42J8Yhhfn31ydFq49w60cZqo0YnbOxhq/y7FYj8gV9IzrPwg2zNe8cmKb/yqVjYwmT67j8Hvg6t2HXe6OzSsBNcVN/vR9d0SZP0DQyz8AXWKXtDniBN2pOojarYYHKQiNivhkCWedrgw5yCR9T84w5jWJ4UAwLfKMS7r/6SVAW5lPRfYSIqBSBJZIs/WXVBefds0aFrBW1LyqQSt1Hvpt71CMT3QHaNTZ9Vws0ddgW66KqpyZRHrS+fhphwHLy2NNXVAgmFcRs=
  on:
    branch: master
after_deploy:
- cd gulp
- ./node_modules/.bin/sentry-cli releases set-commits "$VERSION" --auto
- ./node_modules/.bin/sentry-cli releases finalize "$VERSION"
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: O6GDqr2TbHf5QA2iKJjErcZi0MsAoz3OnGTanAxyjJnK/1qr7K/FdMUv6pOZo0Nu05/P4bvll7Xn4y5C9EynaXc53d77eqcrXttbXzFD1WQ/UHr67waYOQPRN/wCPFDmxZsgSzakSAhD2JGPT+dFENrRVuPw7PmZXlKVDNa/W0MlqghvyDb/OH3o16W+5gmFvGVeCg5Bst54K77/V5uzWu34fgIzT1YZshCRn3LGoV5yOBmzXWjA5bJ56PAcXsD3aoWUZNNdb4jdqOJVffpKmqTbEe3MvvzuedkCJE3KmBpHkpb7yWBFFiwzFsJQaDEpQdQoUrWFM1mOTc91VNPfpghJ0AVhQMG4yTzi3klN1jYLpDh5BFUi0J7D2ttnDvfCZk7xRwt2X1o8lnDvEuEAdNL5BdbZWdhBsxVO4BwGR6aj5PI5m25TBdMgTgcniqzfD68E926p4/UqGc8hJJ2LaDYf0CNz99ej2PW5rEtfAbEl0NqfSD9x4oMNMn/Wh/Px5P1WxGDxTNb0HhYxPuyjInbk6jj0orDwa09p3vdICz30RLNZ/ip2cJBUHdAd9qyAul9d9LIu7hzmktNBXJ6hGE+QP2NlWhC4b3ykA20m7iFjxhRbyn5CFOPZTOJgmqL9eG+eFSrq00j98QfYF9Imhrpa5yQa8H59HTOI2n+gtuA=
  - secure: NKsQK0kkdBptAI4ZuRIZAUVPKxhBmS7dDSi0L6T1z3OOXYytKmvMyBWaF8pCNIjVwMjigtK8rpgXbji4tRQtpEKSYjZEQhGr/YV5RQpRtHjAq1g/LG1FcdYpXg6IpZC36YtEj69sLxq1ZndlDSCXXXG+D6ZOMbQHOzS5xff7znZEYSYqhexH0/a4zwhK3Ks9rgpRfdejvOTKL8uiaQJ/lW34uy2yjv8rCMsh0+gF3VDAUwh5muqbdoPFBlBGle/CV/e24gVt41vyWIZmAqe8KeEw35fTaIOBZSkBhBUTuKdIb2NwYDn3vnqT08X/8pI5/+n5+EsUg6C6J+4az6b2NTeo4WKkRZ/0FGvBGbofNrVvqi9g3Q7yTdgn2tXT4dAVYy5ypKW0YC4ZBrNkpR/P5cbCBzBgGYyyoyzmqEK4BXRBL74ehdFkxV/yVh4nSRg+hYRGjnYmWSBsdrP8I/2gfzNjtEaAA3tSoGFCgc4vab65eihaJIooNwXC5AKTgWsOaB8HVd0gKrlD17EcdZFZdxAjCyK1uhjmP6Nf9HBszetLXFOn8hnWc94CgynBoAdWTZ+ClJPJES6g27bgxVPDqliTjDyyuXYzF6ShcDE9SF+0zQNXbM2xpckYeFanA1Ak7RaeEvwOMASbSGYilLDHb4HrcikRH83znZbN8Q9LNQ8=
  - secure: WFGakkWzO6c84Xpev0g4GaDy6Sl8RcZgcDtDpDFxQ3Tnly1Mh/LDGjxZ5XCgWGrsNr1zUilfILhFET5OCCK0gnkSWFFxuku64q1IY2ctH+0zU753w8fKUHaI1NxQljvR/by52QtBYPlNW22wrCxJ7KpBriYx+OzRqZl37b566tN2F75aBM7nATTKZtGwe6VIQsZAYPyzELGcnKxKB1INVsVvLmfebJMMNBj3e23A3mhyHeSsgXb6Mse7g41kLUszb6tmemYgP0Wjav2hcipjYpiXX8cbYmBE/uUVIzi9PDSiuQYrA5Vw8dmlK81Wyfe+Ii9IOc2OVJA799yIo/nvmeyBnNs+DgMhkN6onHdYaxhyO2L0iYgSoAmkPa6YtZhZDza8Oy8KC6XHCSpxjie2e5JjnMyRDPNiPOEv2PKiCffWUOFu2FPk0x2L5CfxZ+ahchauusR6V9aIYuub0ivlqwMgBQShMmmpPZWH3cOh28YtsTPg4OpI9u0RpvhQPPL4qc73LSpCeZ/KeHOkMQy9Lj8D7zcdHQvqfxjyngiV9kyz4ks7spp4KL0+fflGFmTvaoZl5x5RU8meAFkZTyctPR5646gaNKJdc5f0KxAsFxwWglIJgc6qKwiftQc+ylm6kazdIGkjsHO0FeIRkOBZL+qbqNLMCcWV/yc0hfJJADM=
notifications:
  slack:
    rooms:
      secure: B7BsC9oM9T6ISekAJNv6UpZmI5Y3ztIsDaawHhhegZzna2j1Q2syZhpFd9PGs/NnwEjm0zjqpZyMLd7+9lml/NSG7BM0QRZv74AuxydLybJYz2aoPj9BP3tsjueadpwuNJPp1gYGjN0/YxZDQh8AvV8tP2KPRQ+JFZ9M0WegQfdzd1w0yS8B+JyeiE3BFQnIkQKOQw9BAhM4hOvlNfN5ABhOZ4yD20rvPtdUwuL7HyUNb1/obEiiPCKYFfFpzwwouCOWaSQhv8Uijy4ylt2gIIG6/zV/JOILxRrizUQF3uSUfzKLOZDMxDzyZ9Zjl0hEQ18Knh8Q1ClLoVqu74WQeEpBFuU75NwlYTgDVCsXA8zw/mDynGsOgbhWumTskPwm2y74mmr7tYlG9WshovKJMTqYyZdrCC02pq0yGXbVI9jIWJn+hpt2XWu/uArDchD68fkItygA6gBX2a5hF99fpVI5X3FP++fP9gXljKSiJYRCsp5lD2lQuVKU7Znzv+XBbg6YXaJAM/4W44BfUZ2eCJkyaE6PGPgWAIkQoLzsIiGhZ3RvSBEP+VGmfIdn/wD2R+o1JLCm+OkYX7J+4UeDJtgmBD6knj2q2kSrdlbGBwKaXLQ4fhQcTn4ohagmsgeMT8elyR2c+w1gLxng4ocLVPxSKo4krEAQ4qET1g9T3Ww=
